theme: jekyll-theme-cayman
title: beJS Assertion framework
description: beJS is a simple and light-weight assertions framework for javascript
google_analytics: UA-101992896-1
repository_name: beJS
repository_url: https://github.com/fabioricali/beJS
owner_name: Fabio Ricali
owner_url: http://rica.li
author:
  name:       Fabio Ricali
  url:        http://rica.li
  name:       Davide Polano
  url:        https://www.mdslab.org
